load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "manager",
    srcs = [
        "SeleniumManager.java",
        "SeleniumManagerOutput.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/devtools/v137",
        "//java/src/org/openqa/selenium/os",
    ],
)
