load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "internal",
    srcs = [
        "ImageSummary.java",
        "Reference.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/docker"],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/devtools/v137",
        "//java/src/org/openqa/selenium/docker",
        "@maven//:com_google_guava_guava",
    ],
)
