load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "empty",
    srcs = [
        "NullAttributeMap.java",
        "NullContext.java",
        "NullPropagator.java",
        "NullSpan.java",
        "NullTracer.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/remote:remote_export"],
    deps = [
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/remote:remote_export",
    ],
)
