load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "firefox",
    srcs = [
        "AddHasContext.java",
        "AddHasExtensions.java",
        "AddHasFullPageScreenshot.java",
        "ClasspathExtension.java",
        "Executable.java",
        "Extension.java",
        "FileExtension.java",
        "FirefoxBinary.java",
        "FirefoxCommandContext.java",
        "FirefoxDriver.java",
        "FirefoxDriverLogLevel.java",
        "FirefoxDriverService.java",
        "FirefoxOptions.java",
        "FirefoxProfile.java",
        "GeckoDriverInfo.java",
        "GeckoDriverService.java",
        "HasContext.java",
        "HasExtensions.java",
        "HasFullPageScreenshot.java",
        "Preferences.java",
        "ProfilesIni.java",
        "UnableToCreateProfileException.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/remote:remote_export",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/devtools/v137",
        "//java/src/org/openqa/selenium/remote:remote_export",
        "@maven//:com_google_auto_service_auto_service_annotations",
    ],
)
