load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "webextension",
    srcs = [
        "ExtensionArchivePath.java",
        "ExtensionBase64Encoded.java",
        "ExtensionData.java",
        "ExtensionPath.java",
        "InstallExtensionParameters.java",
        "UninstallExtensionParameters.java",
        "WebExtension.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/remote:remote_export",
    ],
)
