load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "httpd",
    srcs = [
        "DefaultNodeConfig.java",
        "NodeServer.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/netty/server",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/cli",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/events",
        "//java/src/org/openqa/selenium/grid",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/log",
        "//java/src/org/openqa/selenium/grid/node",
        "//java/src/org/openqa/selenium/grid/node/config",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/netty/server",
        "//java/src/org/openqa/selenium/remote:remote_export",
        "@maven//:com_google_auto_service_auto_service_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:dev_failsafe_failsafe",
    ],
)
