load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "remote",
    srcs = ["RemoteNewSessionQueue.java"],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/sessionqueue",
        "//java/src/org/openqa/selenium/remote:remote_export",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/log",
        "//java/src/org/openqa/selenium/grid/security",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/grid/sessionqueue",
        "//java/src/org/openqa/selenium/grid/sessionqueue/config",
        "//java/src/org/openqa/selenium/grid/web",
        "//java/src/org/openqa/selenium/remote:remote_export",
    ],
)
