load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "ui",
    srcs = [
        "ExpectedCondition.java",
        "ExpectedConditions.java",
        "FluentWait.java",
        "ISelect.java",
        "LoadableComponent.java",
        "Quotes.java",
        "Select.java",
        "Sleeper.java",
        "SlowLoadableComponent.java",
        "UnexpectedTagNameException.java",
        "Wait.java",
        "WebDriverWait.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium:core"],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/remote:remote_export",
        "@maven//:com_google_guava_guava",
    ],
)
