load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "codec",
    srcs = [
        "AbstractHttpCommandCodec.java",
        "AbstractHttpResponseCodec.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/devtools/v137",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
    ],
)
