load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "chromium",
    srcs = [
        "AddHasCasting.java",
        "AddHasCdp.java",
        "AddHasLaunchApp.java",
        "AddHasNetworkConditions.java",
        "AddHasPermissions.java",
        "ChromiumDriver.java",
        "ChromiumDriverCommandExecutor.java",
        "ChromiumDriverInfo.java",
        "ChromiumDriverLogLevel.java",
        "ChromiumNetworkConditions.java",
        "ChromiumOptions.java",
        "HasCasting.java",
        "HasCdp.java",
        "HasLaunchApp.java",
        "HasNetworkConditions.java",
        "HasPermissions.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/remote:remote_export",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/devtools/v135",
        "//java/src/org/openqa/selenium/devtools/v137",
        "//java/src/org/openqa/selenium/remote:remote_export",
        "@maven//:com_google_auto_service_auto_service_annotations",
    ],
)
